version: '2'

services:
  
#Nginx
  web:
    image: nginx:1.13.8
    depends_on:
      - backend
    ports:
        - "80:80"
        - "443:443"
    volumes:
        - ./nginx/conf.d:/etc/nginx/conf.d
        - ./app:/code
    depends_on:
      - backend

#Python
  backend:
    build: .
    command: ["gunicorn", "--workers=8", "--bind=0.0.0.0:5000", "todo-list:app"]
    ports:
      - "5000:5000"
    volumes:
      - ./app:/code
