version: '2'

services:
  web:
    build: .
    command: ['python','todo-list.py']
    ports:
      - "5000:5000"
    volumes:
      - ./app:/code

#   percona:
#     image: percona
#     restart: always
#     #volumes:
#     #    - ./database/mysql/data/percona:/var/lib/mysql
#     ports:
#         - 3306:3306
#     environment:
#         - MYSQL_ROOT_PASSWORD=root
#         - MYSQL_DATABASE=TODO_LIST
#         - MYSQL_USER=flask
#         - MYSQL_PASSWORD=123

#   phpmyadmin:
#     image: phpmyadmin/phpmyadmin
#     restart: always
#     environment:
#         PMA_ARBITRARY: 1
#     ports:
#         - 8888:80
#     volumes:
#         - /sessions