version: '2'

services:
#Python
  backend:
    build: .
    command: ['python','todo-list.py']
    mem_limit: 512M
    ports:
      - "80:5000"
    volumes:
      - ./app:/code
    links:
      - elasticsearch
      - mongo

#ElasticSeach
  elasticsearch:
    image: elasticsearch:latest
    mem_limit: 3G
    ports:
      - "9200:9200"
      - "9300:9300"

#Mongo
  mongo:
    image: mongo
    mem_limit: 1G
    ports:
      - "27017:27017"
    volumes:
      - /data/db
      - /data/configdb

#MailHog idea de um amigo
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "8025:8025"